# -*- coding: utf-8 -*-
"""tax_calculator .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPdvBygKB2boX5JlY1awYdqAsCM-9vnP
"""

# Pakistan Small Business Tax Calculator
# Tax Year 2025-26
# For Individual / Sole Proprietor

# -------------------------------
# Step 1: Income Inputs
# -------------------------------
gross_income = float(input("Enter Gross Business Income (PKR): "))
other_income = float(input("Enter Other Income (PKR): "))

# -------------------------------
# Step 2: Expense Inputs
# -------------------------------
cogs = float(input("Enter Cost of Goods Sold (PKR): "))
salaries = float(input("Enter Salaries & Wages (PKR): "))
rent_utilities = float(input("Enter Rent & Utilities (PKR): "))
marketing = float(input("Enter Marketing & Advertising (PKR): "))
depreciation = float(input("Enter Depreciation (PKR): "))
other_expenses = float(input("Enter Other Business Expenses (PKR): "))

# -------------------------------
# Step 3: Total Income & Expenses
# -------------------------------
total_income = gross_income + other_income

total_expenses = (
    cogs +
    salaries +
    rent_utilities +
    marketing +
    depreciation +
    other_expenses
)

# -------------------------------
# Step 4: Net Taxable Income
# -------------------------------
net_income = total_income - total_expenses

# -------------------------------
# Step 5: Tax Calculation (FBR Slabs 2025-26)
# -------------------------------
if net_income <= 600000:
    tax = 0

elif net_income <= 1200000:
    tax = (net_income - 600000) * 0.01

elif net_income <= 2200000:
    tax = 6000 + (net_income - 1200000) * 0.11

elif net_income <= 3200000:
    tax = 116000 + (net_income - 2200000) * 0.23

elif net_income <= 4100000:
    tax = 346000 + (net_income - 3200000) * 0.30

else:
    tax = 616000 + (net_income - 4100000) * 0.35

# -------------------------------
# Step 6: Output Result
# -------------------------------
print("\n------ TAX CALCULATION SUMMARY ------")
print("Total Income (PKR):", total_income)
print("Total Expenses (PKR):", total_expenses)
print("Net Taxable Income (PKR):", net_income)
print("Tax Payable (PKR):", round(tax, 2))

